name: error-control-statistical-tests-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - pandas
  - pandasql
  - scikit-learn
  -pip:
    - scikit-optimize
